modLoader="javafml"
loaderVersion="[2,)"
license="Not specified"

[[mods]]
modId="the_dungeon_of_luck"
version="1.0.0"
displayName="The dungeon of luck!"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="storm, MCreator"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.the_dungeon_of_luck]]
    modId="neoforge"
    type="required"
    versionRange="[20.4.223,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.the_dungeon_of_luck]]
    modId="minecraft"
    type="required"
    versionRange="[1.20.4]"
    ordering="NONE"
    side="BOTH"



